#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: SakuraKnot
main: com.kumoe.sakura_knot.SakuraKnot
version: 0.0.1
api-version: 1.13
website: https://www.peacefulcraft.net/
depend: [ CMI, Vault ]
softdepend: []
